// source: p7stream.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.stakeStream.StakeUpdateRequest', null, global);
goog.exportSymbol('proto.stakeStream.StakeUpdateRequest.StakeProgress', null, global);
goog.exportSymbol('proto.stakeStream.StakeUpdateRequest.UpdateType', null, global);
goog.exportSymbol('proto.stakeStream.StakeUpdateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stakeStream.StakeUpdateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stakeStream.StakeUpdateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stakeStream.StakeUpdateRequest.displayName = 'proto.stakeStream.StakeUpdateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stakeStream.StakeUpdateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stakeStream.StakeUpdateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stakeStream.StakeUpdateResponse.displayName = 'proto.stakeStream.StakeUpdateResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stakeStream.StakeUpdateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.stakeStream.StakeUpdateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stakeStream.StakeUpdateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stakeStream.StakeUpdateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    updatetype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stakeid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    referenceid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    soldpercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    offeredpercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    adjuststackmarkup: (f = msg.getAdjuststackmarkup()) && google_protobuf_wrappers_pb.FloatValue.toObject(includeInstance, f),
    stakeprogress: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stakeStream.StakeUpdateRequest}
 */
proto.stakeStream.StakeUpdateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stakeStream.StakeUpdateRequest;
  return proto.stakeStream.StakeUpdateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stakeStream.StakeUpdateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stakeStream.StakeUpdateRequest}
 */
proto.stakeStream.StakeUpdateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.stakeStream.StakeUpdateRequest.UpdateType} */ (reader.readEnum());
      msg.setUpdatetype(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStakeid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReferenceid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSoldpercent(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setOfferedpercent(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.FloatValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.FloatValue.deserializeBinaryFromReader);
      msg.setAdjuststackmarkup(value);
      break;
    case 7:
      var value = /** @type {!proto.stakeStream.StakeUpdateRequest.StakeProgress} */ (reader.readEnum());
      msg.setStakeprogress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stakeStream.StakeUpdateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stakeStream.StakeUpdateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stakeStream.StakeUpdateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stakeStream.StakeUpdateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdatetype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStakeid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getReferenceid();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getSoldpercent();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getOfferedpercent();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getAdjuststackmarkup();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.FloatValue.serializeBinaryToWriter
    );
  }
  f = message.getStakeprogress();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.stakeStream.StakeUpdateRequest.UpdateType = {
  INFO: 0,
  STATUS: 1
};

/**
 * @enum {number}
 */
proto.stakeStream.StakeUpdateRequest.StakeProgress = {
  PROCESSING: 0,
  CANCELED: 1
};

/**
 * optional UpdateType updateType = 1;
 * @return {!proto.stakeStream.StakeUpdateRequest.UpdateType}
 */
proto.stakeStream.StakeUpdateRequest.prototype.getUpdatetype = function() {
  return /** @type {!proto.stakeStream.StakeUpdateRequest.UpdateType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.stakeStream.StakeUpdateRequest.UpdateType} value
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
 */
proto.stakeStream.StakeUpdateRequest.prototype.setUpdatetype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 stakeId = 2;
 * @return {number}
 */
proto.stakeStream.StakeUpdateRequest.prototype.getStakeid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
 */
proto.stakeStream.StakeUpdateRequest.prototype.setStakeid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 referenceId = 3;
 * @return {number}
 */
proto.stakeStream.StakeUpdateRequest.prototype.getReferenceid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
 */
proto.stakeStream.StakeUpdateRequest.prototype.setReferenceid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional float soldPercent = 4;
 * @return {number}
 */
proto.stakeStream.StakeUpdateRequest.prototype.getSoldpercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
 */
proto.stakeStream.StakeUpdateRequest.prototype.setSoldpercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float offeredPercent = 5;
 * @return {number}
 */
proto.stakeStream.StakeUpdateRequest.prototype.getOfferedpercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
 */
proto.stakeStream.StakeUpdateRequest.prototype.setOfferedpercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional google.protobuf.FloatValue adjustStackMarkup = 6;
 * @return {?proto.google.protobuf.FloatValue}
 */
proto.stakeStream.StakeUpdateRequest.prototype.getAdjuststackmarkup = function() {
  return /** @type{?proto.google.protobuf.FloatValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.FloatValue, 6));
};


/**
 * @param {?proto.google.protobuf.FloatValue|undefined} value
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
*/
proto.stakeStream.StakeUpdateRequest.prototype.setAdjuststackmarkup = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
 */
proto.stakeStream.StakeUpdateRequest.prototype.clearAdjuststackmarkup = function() {
  return this.setAdjuststackmarkup(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stakeStream.StakeUpdateRequest.prototype.hasAdjuststackmarkup = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional StakeProgress stakeProgress = 7;
 * @return {!proto.stakeStream.StakeUpdateRequest.StakeProgress}
 */
proto.stakeStream.StakeUpdateRequest.prototype.getStakeprogress = function() {
  return /** @type {!proto.stakeStream.StakeUpdateRequest.StakeProgress} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.stakeStream.StakeUpdateRequest.StakeProgress} value
 * @return {!proto.stakeStream.StakeUpdateRequest} returns this
 */
proto.stakeStream.StakeUpdateRequest.prototype.setStakeprogress = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stakeStream.StakeUpdateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.stakeStream.StakeUpdateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stakeStream.StakeUpdateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stakeStream.StakeUpdateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stakeStream.StakeUpdateResponse}
 */
proto.stakeStream.StakeUpdateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stakeStream.StakeUpdateResponse;
  return proto.stakeStream.StakeUpdateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stakeStream.StakeUpdateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stakeStream.StakeUpdateResponse}
 */
proto.stakeStream.StakeUpdateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stakeStream.StakeUpdateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stakeStream.StakeUpdateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stakeStream.StakeUpdateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stakeStream.StakeUpdateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.stakeStream.StakeUpdateResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.stakeStream.StakeUpdateResponse} returns this
 */
proto.stakeStream.StakeUpdateResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.stakeStream);
