export enum AccountGroup {
    Normal,
    Floorman,
    Administrators,
    Master,
}

export enum Currency {
    USD = 0,
    EUR = 1,
    GBP = 2,
    RUB = 3,
    JPY = 4,
    KRW = 5,
    CNY = 6,
    HKD = 7,
    TWD = 8,
    KHR = 9,
    VND = 10,
    PHP = 11,
    INR = 12,
    THB = 13,
    IDR = 14,
    MYR = 15,
    SGD = 16,
    SEK = 17,
    NOK = 18,
    CHF = 19,
    CAD = 20,
    AMD = 21,
    DKK = 22,
    GCD = 23,
    GTD = 24,
    AUD = 25,
}

export enum CurrencySymbol {
    USD = '$',
    EUR = '€',
    GBP = '£',
    RUB = '₽',
    JPY = '¥',
    CNY = '¥',
    KRW = '₩',
    AUD = 'A$',
    CAD = 'Can$',
}

export enum DateSearchOptions {
    AnyDate = 'AnyDate',
    Today = 'Today',
    Yesterday = 'Yesterday',
    ThisWeek = 'This Week',
    LastWeek = 'Last Week',
    ThisMonth = 'This Month',
    LastMonth = 'Last Month',
    CustomRange = 'Custom Range',
    Before24Hours = '24Hours Ago',
}

export enum TimezoneEnums {
    'UTC-11' = -11,
    'UTC-10' = -10,
    'UTC-9' = -9,
    'UTC-8' = -8,
    'UTC-7' = -7,
    'UTC-6' = -6,
    'UTC-5' = -5,
    'UTC-4.5' = -4.5,
    'UTC-4' = -4,
    'UTC-3.5' = -3.5,
    'UTC-3' = -3,
    'UTC-2' = -2,
    'UTC-1' = -1,
    'UTC+0' = 0,
    'UTC+1' = 1,
    'UTC+2' = 2,
    'UTC+3' = 3,
    'UTC+3.5' = 3.5,
    'UTC+4' = 4,
    'UTC+5' = 5,
    'UTC+5.5' = 5.5,
    'UTC+5.75' = 5.75,
    'UTC+6' = 6,
    'UTC+6.5' = 6.5,
    'UTC+7' = 7,
    'UTC+8' = 8,
    'UTC+9' = 9,
    'UTC+9.5' = 9.5,
    'UTC+10' = 10,
    'UTC+10.5' = 10.5,
    'UTC+11' = 11,
    'UTC+12' = 12,
    'UTC+13' = 13,
}
